[project]
name = "ecoroof-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain>=0.3.26",
    "openai>=1.93.0",
    "python-dotenv>=1.1.1",
    "streamlit>=1.46.1",
]
